# Generated by Django 4.0.1 on 2022-06-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto1',
            old_name='mansaje',
            new_name='mensaje',
        ),
    ]
