# Generated by Django 4.0.1 on 2022-06-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_mansaje_contacto1_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto1',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'Sugerencias'], [3, 'Felicitaciones']]),
        ),
    ]
